name             'testbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures testbook'
long_description 'Installs/Configures testbook'
version          '0.1.0'
